# Generated by Django 5.1.6 on 2025-03-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel_de_acesso',
            field=models.IntegerField(default=1),
        ),
    ]
