# Generated by Django 5.0.7 on 2025-03-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrada', models.IntegerField(auto_created=True, default=100)),
                ('produtos_entrada', models.ManyToManyField(related_name='produtos_entrada', to='produto.produto')),
            ],
        ),
    ]
