# Generated by Django 5.1.6 on 2025-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0003_produto_responsavel_conserto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrada', models.IntegerField(auto_created=True, default=100)),
                ('produtos_entrada', models.ManyToManyField(related_name='produtos_entrada', to='produto.produto')),
            ],
        ),
    ]
