# Generated by Django 5.1.6 on 2025-03-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrada', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='produtos_entrada',
            field=models.ManyToManyField(related_name='produtos_entrada', to='produto.produto'),
        ),
    ]
