# Generated by Django 5.0.7 on 2025-03-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=15)),
                ('sufixo', models.CharField(max_length=30)),
                ('part_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('VERIFICAR DISPONIBILIDADE', 'VERIFICAR DISPONIBILIDADE'), ('LIBERADO PARA CONSERTO', 'LIBERADO PARA CONSERTO'), ('AGUARDANDO PEÇA', 'AGUARDANDO PEÇA')], max_length=30)),
                ('descricao', models.CharField(max_length=15)),
                ('observacao', models.CharField(max_length=15)),
            ],
        ),
    ]
