# Generated by Django 5.1.6 on 2025-03-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('VERIFICAR DISPONIBILIDADE', 'VERIFICAR DISPONIBILIDADE'), ('AGUARDANDO PEÇA', 'AGUARDANDO PEÇA'), ('LIBERADO PARA CONSERTO', 'LIBERADO PARA CONSERTO')], default='VERIFICAR DISPONIBILIDADE', max_length=30)),
                ('defeito_pecas', models.CharField(blank=True, choices=[('ND', ' '), ('NÃO LIGA', 'NÃO LIGA'), ('RISCADO', 'RISCADO'), ('OXIDADO', 'OXIDADO'), ('MANCHADO', 'MANCHADO'), ('FALTANTE', 'FALTANTE')], default='ND', max_length=255, null=True)),
                ('posicao', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('numero_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_peca', models.CharField(blank=True, choices=[('01', 'Garantia'), ('02', 'Orçamento')], max_length=255, null=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='sku.sku')),
                ('sufixo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='sku.sufixo')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VERIFICAR DISPONIBILIDADE', 'VERIFICAR DISPONIBILIDADE'), ('AGUARDANDO PEÇA', 'AGUARDANDO PEÇA'), ('LIBERADO PARA CONSERTO', 'LIBERADO PARA CONSERTO')], default='VERIFICAR DISPONIBILIDADE', max_length=30)),
                ('defeito_peca', models.CharField(blank=True, choices=[('ND', ' '), ('NÃO LIGA', 'NÃO LIGA'), ('RISCADO', 'RISCADO'), ('OXIDADO', 'OXIDADO'), ('MANCHADO', 'MANCHADO'), ('FALTANTE', 'FALTANTE')], max_length=255, null=True)),
                ('tipo_peca', models.CharField(blank=True, choices=[('01', 'Garantia'), ('02', 'Orçamento')], max_length=255, null=True)),
                ('numero_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtopecas', to='pecas.peca')),
            ],
        ),
    ]
