# Generated by Django 5.0.7 on 2025-03-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopeca',
            name='defeito_peca',
            field=models.CharField(blank=True, choices=[('ND', ' '), ('NÃO LIGA', 'NÃO LIGA'), ('RISCADO', 'RISCADO'), ('OXIDADO', 'OXIDADO'), ('MANCHADO', 'MANCHADO'), ('FALTANTE', 'FALTANTE')], max_length=255, null=True),
        ),
    ]
