# Generated by Django 5.0.7 on 2025-03-05 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0001_initial'),
        ('sku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='peca',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='peca',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='sku.sku'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='status',
            field=models.CharField(choices=[('VERIFICAR DISPONIBILIDADE', 'VERIFICAR DISPONIBILIDADE'), ('AGUARDANDO PEÇA', 'AGUARDANDO PEÇA'), ('LIBERADO PARA CONSERTO', 'LIBERADO PARA CONSERTO')], default='VERIFICAR DISPONIBILIDADE', max_length=30),
        ),
        migrations.AlterField(
            model_name='peca',
            name='sufixo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas', to='sku.sufixo'),
        ),
    ]
