# Generated by Django 5.0.7 on 2025-03-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopeca',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
