# Generated by Django 5.0.7 on 2025-03-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0002_alter_peca_descricao_alter_peca_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='posicao',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
