# Generated by Django 5.0.7 on 2025-03-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0003_produtopeca_tipo_peca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='tipo_peca',
        ),
    ]
