# Generated by Django 5.0.7 on 2025-03-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0003_peca_posicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='defeito_pecas',
            field=models.CharField(choices=[('NÃO LIGA', 'NÃO LIGA'), ('RISCADO', 'RISCADO'), ('OXIDADO', 'OXIDADO'), ('MANCHADO', 'MANCHADO'), ('FALTANTE', 'FALTANTE')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
