# Generated by Django 5.0.7 on 2025-03-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0004_remove_peca_tipo_peca'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='tipo_peca',
            field=models.CharField(blank=True, choices=[('01', 'Garantia'), ('02', 'Orçamento')], max_length=255, null=True),
        ),
    ]
