# Generated by Django 5.0.7 on 2025-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0004_peca_defeito_pecas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='defeito_pecas',
            field=models.CharField(choices=[('ND', ''), ('NÃO LIGA', 'NÃO LIGA'), ('RISCADO', 'RISCADO'), ('OXIDADO', 'OXIDADO'), ('MANCHADO', 'MANCHADO'), ('FALTANTE', 'FALTANTE')], default='ND', max_length=30),
        ),
    ]
