# Generated by Django 5.0.7 on 2025-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0006_alter_peca_defeito_pecas'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='numero_pedido',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peca',
            name='tipo_peca',
            field=models.CharField(choices=[('01', 'Garantia'), ('02', 'Orçamento')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
