# Generated by Django 5.0.7 on 2025-03-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0007_peca_numero_pedido_peca_tipo_peca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peca',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
