# Generated by Django 5.1.6 on 2025-02-21 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sku', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('TRIAGEM', 'TRIAGEM'), ('CONSERTO', 'CONSERTO'), ('VERIFICAR DISPONIBILIDADE', 'VERIFICAR DISPONIBILIDADE'), ('AGUARDANDO PEÇA', 'AGUARDANDO PEÇA'), ('LIBERADO PARA CONSERTO', 'LIBERADO PARA CONSERTO'), ('EMBALAGEM', 'EMBALAGEM'), ('ENCERRADO', 'ENCERRADO')], default='ENTRADA', max_length=30)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('ptn', models.CharField(max_length=15)),
                ('serie', models.CharField(max_length=30)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produto_sku', to='sku.sku')),
            ],
        ),
    ]
