# Generated by Django 5.0.7 on 2025-03-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_saida',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='numero_registro',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
