# Generated by Django 5.0.7 on 2025-03-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('TRIAGEM', 'TRIAGEM'), ('CONSERTO', 'CONSERTO'), ('VERIFICAR DISPONIBILIDADE', 'VERIFICAR DISPONIBILIDADE'), ('AGUARDANDO PEÇA', 'AGUARDANDO PEÇA'), ('LIBERADO PARA CONSERTO', 'LIBERADO PARA CONSERTO'), ('EMBALAGEM', 'EMBALAGEM'), ('EMBALADO', 'EMBALADO'), ('ENCERRADO', 'ENCERRADO')], default='ENTRADA', max_length=30),
        ),
    ]
