# Generated by Django 5.1.6 on 2025-02-21 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('sku', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produto_modelo_sku', to='sku.sku'),
            preserve_default=False,
        ),
    ]
