# Generated by Django 5.0.7 on 2025-03-16 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_data_saida_produto_numero_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_saida',
        ),
    ]
