# Generated by Django 5.0.7 on 2025-03-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_data_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='impresso',
            field=models.BooleanField(default=False),
        ),
    ]
