# Generated by Django 5.1.6 on 2025-02-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
        ('produto', '0002_produto_modelo'),
        ('sku', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='responsavel_conserto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_conserto', to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='produto',
            name='responsavel_embalagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_embalagem', to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='produto',
            name='responsavel_entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_entrada', to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='produto',
            name='responsavel_saida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_saida', to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='produto',
            name='responsavel_triagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_triagem', to='funcionario.funcionario'),
        ),
        migrations.AddField(
            model_name='produto',
            name='sufixo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produto_sufixo', to='sku.sufixo'),
            preserve_default=False,
        ),
    ]
