# Generated by Django 5.1.6 on 2025-02-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
        ('produto', '0003_produto_responsavel_conserto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='responsavel_conserto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_conserto', to='funcionario.funcionario'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='responsavel_embalagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_embalagem', to='funcionario.funcionario'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='responsavel_entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_entrada', to='funcionario.funcionario'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='responsavel_saida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_saida', to='funcionario.funcionario'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='responsavel_triagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsavel_triagem', to='funcionario.funcionario'),
        ),
    ]
