# Generated by Django 5.1.6 on 2025-02-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_defeito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='defeito',
            field=models.CharField(choices=[('SEM DEFEITO', 'SEM DEFEITO'), ('ESTÉTICO', 'ESTÉTICO'), ('ESTÉTICO-FUNCIONAL', 'ESTÉTICO-FUNCIONAL'), ('FUNCIONAL', 'FUNCIONAL'), ('VENDA DIRETA', 'VENDA DIRETA')], default='1', max_length=30),
        ),
    ]
