# Generated by Django 5.1.6 on 2025-02-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_defeito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_de_defeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEM DEFEITO', 'SEM DEFEITO'), ('ESTÉTICO', 'ESTÉTICO'), ('ESTÉTICO-FUNCIONAL', 'ESTÉTICO-FUNCIONAL'), ('FUNCIONAL', 'FUNCIONAL'), ('VENDA DIRETA', 'VENDA DIRETA')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='defeito',
        ),
    ]
