# Generated by Django 5.1.6 on 2025-02-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_tipo_de_defeito_remove_produto_defeito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tipo_de_defeito',
        ),
        migrations.AddField(
            model_name='produto',
            name='defeito',
            field=models.CharField(choices=[('1', 'SEM DEFEITO'), ('2', 'ESTÉTICO'), ('3', 'ESTÉTICO-FUNCIONAL'), ('4', 'FUNCIONAL'), ('5', 'VENDA DIRETA')], default='1', max_length=30),
        ),
    ]
