# Generated by Django 5.1.6 on 2025-02-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_produto_defeito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='defeito',
            field=models.CharField(choices=[('01-SEM DEFEITO', 'SEM DEFEITO'), ('02-ESTÉTICO', 'ESTÉTICO'), ('03-ESTÉTICO-FUNCIONAL', 'ESTÉTICO-FUNCIONAL'), ('04-FUNCIONAL', 'FUNCIONAL'), ('05-VENDA DIRETA', 'VENDA DIRETA')], max_length=30),
        ),
    ]
