# Generated by Django 5.1.6 on 2025-02-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_alter_produto_defeito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='defeito',
            field=models.CharField(choices=[(1, 'Estético'), (2, 'Funcional'), (3, 'Estético-Funcional'), (4, 'Sem Defeito')], max_length=30),
        ),
    ]
