# Generated by Django 5.1.6 on 2025-02-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_alter_produto_defeito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='defeito',
            field=models.CharField(choices=[('Estético', 'Estético'), ('Funcional', 'Funcional'), ('Estético-Funcional', 'Estético-Funcional'), ('Sem Defeito', 'Sem Defeito'), ('Venda Direta', 'Venda Direta')], max_length=30),
        ),
    ]
