# Generated by Django 5.0.7 on 2025-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_alter_produto_defeito'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='defeito_especifico',
            field=models.CharField(choices=[('Tela Quebrada', 'Tela Quebrada'), ('Não liga', 'Não liga')], default='Sem Defeito', max_length=30),
        ),
    ]
