# Generated by Django 5.0.7 on 2025-03-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_produto_defeito_especifico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='defeito_especifico',
            field=models.CharField(choices=[('Tela Quebrada', 'Tela Quebrada'), ('Não liga', 'Não liga'), ('Sem Defeito', 'Sem Defeito')], default='Sem Defeito', max_length=30),
        ),
    ]
