# Generated by Django 5.0.7 on 2025-03-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_alter_produto_defeito_especifico'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='observacao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
