# Generated by Django 5.0.7 on 2025-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecas', '0003_peca_posicao'),
        ('produto', '0016_produto_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='peca',
            field=models.ManyToManyField(related_name='produto_pecas', to='pecas.peca'),
        ),
    ]
